/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package riddleproject;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import javax.swing.*;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.*;


public class PlayerPoint extends javax.swing.JFrame{
    Connection con; //variable for databse connection
    Statement st; //variable for the sql
    private PlayerInfo player;
    ArrayList<PlayerInfo> playerList = new ArrayList<>(); 
    
    /**
     * Creates new form playerName
     */
    public PlayerPoint() {
        initComponents();
        makeFullScreenAndCenter();
        player = new PlayerInfo();
        gameRules.setVisible(false);
        rulesList.setEnabled(false);
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gameRules = new javax.swing.JPanel();
        riddleMiniLogo = new javax.swing.JLabel();
        lblRules = new javax.swing.JLabel();
        rulesList = new javax.swing.JScrollPane();
        txtRules = new javax.swing.JTextArea();
        btnClose = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        containerPanel = new javax.swing.JPanel();
        lblPlayer = new javax.swing.JLabel();
        txtPlayerName = new javax.swing.JTextField();
        btnExit = new javax.swing.JButton();
        btnStart1 = new javax.swing.JButton();
        btnRules = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Guess The Riddle - LOGIN");
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gameRules.setBackground(new java.awt.Color(255, 255, 204));
        gameRules.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        gameRules.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        riddleMiniLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        riddleMiniLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_game/mini logo.png"))); // NOI18N
        riddleMiniLogo.setToolTipText("");
        gameRules.add(riddleMiniLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, 62));

        lblRules.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblRules.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRules.setText("GAME RULES");
        gameRules.add(lblRules, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 163, -1));

        txtRules.setColumns(20);
        txtRules.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtRules.setRows(5);
        txtRules.setText("\n1. Answer Correctly: Players must answereach riddle correctly to\nproceed to the next level.\n2. Time Limit: Players have a limited amount of time to answer\neach riddle. If they fail to answer within the time limit, the game ends.\n3. Hint Usage: Players can use hints to help them answer a riddle.\nHowever, hints are limited and must be used wisely.\n4. Level Progression: Players must complete all riddles in a level to\nunlock the next level. Each level contains more challenging riddles.\n5. Scoring: Players earn hint coin for each correct answer within 20 \nseconds.\n6. Game Over: If players answer a riddle incorrectly or run out of\ntime, the game ends. They can choose to play again or return\nto the main menu.\n7. Hint Coins: Players can earn hint coins by answering riddles quickly.\nThese coins can be used to purchase hints in later levels.\n");
        rulesList.setViewportView(txtRules);

        gameRules.add(rulesList, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 440, 240));

        btnClose.setBackground(new java.awt.Color(255, 51, 51));
        btnClose.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnClose.setText("CLOSE");
        btnClose.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        gameRules.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 70, -1));

        getContentPane().add(gameRules, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 550, 390));

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("WELCOME TO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 32, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_game/riddle medium.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 71, 187, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 230, 290));

        containerPanel.setBackground(new java.awt.Color(51, 51, 51));
        containerPanel.setForeground(new java.awt.Color(255, 255, 255));
        containerPanel.setAlignmentX(0.0F);
        containerPanel.setAlignmentY(0.0F);
        containerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPlayer.setBackground(new java.awt.Color(255, 255, 255));
        lblPlayer.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPlayer.setForeground(new java.awt.Color(255, 255, 255));
        lblPlayer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlayer.setText("ENTER PLAYER NAME");
        lblPlayer.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        containerPanel.add(lblPlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 35, -1, -1));
        lblPlayer.getAccessibleContext().setAccessibleDescription("");

        txtPlayerName.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        txtPlayerName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPlayerName.setActionCommand("<Not Set>");
        txtPlayerName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtPlayerName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtPlayerName.setDisabledTextColor(new java.awt.Color(102, 0, 102));
        txtPlayerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlayerNameActionPerformed(evt);
            }
        });
        containerPanel.add(txtPlayerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 67, 270, 41));

        btnExit.setBackground(new java.awt.Color(255, 153, 153));
        btnExit.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnExit.setText("EXIT GAME");
        btnExit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        containerPanel.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 185, 270, 40));

        btnStart1.setBackground(new java.awt.Color(153, 255, 153));
        btnStart1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnStart1.setText("START GAME");
        btnStart1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnStart1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnStart1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStart1ActionPerformed(evt);
            }
        });
        containerPanel.add(btnStart1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 132, 270, 40));

        btnRules.setBackground(new java.awt.Color(255, 255, 204));
        btnRules.setText("RULES");
        btnRules.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRulesActionPerformed(evt);
            }
        });
        containerPanel.add(btnRules, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 254, 85, -1));

        getContentPane().add(containerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 350, 290));

        jLabel2.setBackground(new java.awt.Color(204, 255, 0));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Riddler_imgs/BG_IMG_MYSTIC (1).jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPlayerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlayerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlayerNameActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:    
        this.setVisible(false);
    }//GEN-LAST:event_btnExitActionPerformed
    
    private void makeFullScreenAndCenter() {
        // 1. Set the window to fullscreen maximized
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);

        // 2. Create a background wrapper with GridBagLayout (automatically centers contents)
        javax.swing.JPanel wrapper = new javax.swing.JPanel(new java.awt.GridBagLayout());
        wrapper.setBackground(java.awt.Color.BLACK); // Black borders around the game

        // 3. Grab the original content pane (which holds all your perfectly placed UI elements)
        java.awt.Container originalContentPane = getContentPane();
        
        // 4. Force the original game to stay exactly 750x500 so it doesn't stretch
        originalContentPane.setPreferredSize(new java.awt.Dimension(750, 500));
        originalContentPane.setMinimumSize(new java.awt.Dimension(750, 500));
        originalContentPane.setMaximumSize(new java.awt.Dimension(750, 500));

        // 5. Place the whole original game inside the center of the black wrapper
        wrapper.add(originalContentPane);

        // 6. Set the wrapper as the new base screen of the JFrame
        setContentPane(wrapper);
    }
    
    private void btnStart1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStart1ActionPerformed
            String playerName = txtPlayerName.getText();

            try {
            if(playerName.isEmpty()){
                JOptionPane.showMessageDialog(null, "Player Name Required", "USER DENIED", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            
            if(checkPlayerExists(playerName)){
            
                try {
                    con = DriverManager.getConnection("jdbc:mysql://localhost:3306/riddlegamedata", "root", "root");
                    String sql = "SELECT * from playerdata WHERE name = '"+ playerName + "'";
                    st = con.createStatement();
                    ResultSet rs = st.executeQuery(sql);
                        if(rs.next()) {
                            PlayerInfo existingPlayer = new PlayerInfo(rs.getString("name"), Integer.parseInt(rs.getString("hintcoin")), Integer.parseInt(rs.getString("level")));
                            playerList.add(existingPlayer);
                            RiddleGameMain start = new RiddleGameMain(existingPlayer);
                            start.setVisible(true);
                            this.setVisible(false);
                        }
                } catch (SQLException ex) {
                    java.util.logging.Logger.getLogger(PlayerPoint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
          
            }else{
                player.setName(playerName);
                player.setLevel(1);
                player.setHintCoin(0);
                
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/riddlegamedata", "root", "root");
                String sql = "INSERT INTO playerdata(name,hintcoin,level) " + " VALUES('" + player.getName() + "' , '" + player.getHintCoin() + "','" + player.getLevel()+ "')";        
                st = con.createStatement();
                st.execute(sql);
                
                this.setVisible(false);

                RiddlerStart story = new RiddlerStart();
                story.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE); 
                story.setVisible(true);

                story.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosed(java.awt.event.WindowEvent e) {
                        try {
                            RiddleGameMain start = new RiddleGameMain(player);
                            start.setVisible(true);
                        } catch (SQLException ex) {
                            java.util.logging.Logger.getLogger(PlayerPoint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                        }
                    }
                });
            }  
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(PlayerPoint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnStart1ActionPerformed

    
    private boolean checkPlayerExists(String playerName) throws SQLException {
        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/riddlegamedata", "root", "root");
        String sql = "SELECT * FROM playerdata WHERE name='" + playerName + "'";
        st = con.createStatement();

        try (ResultSet rs = st.executeQuery(sql)) {
            return rs.next();
    }
}
    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        txtPlayerName.setEnabled(true);
        gameRules.setVisible(false);
        btnStart1.setEnabled(true);
        btnExit.setEnabled(true);
        btnRules.setEnabled(true);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnRulesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRulesActionPerformed
        // TODO add your handling code here:
        txtPlayerName.setEnabled(false);
        btnRules.setEnabled(false);
        gameRules.setVisible(true);
        btnStart1.setEnabled(false);
        btnExit.setEnabled(false);
        txtRules.setEditable(false);
    }//GEN-LAST:event_btnRulesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlayerPoint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlayerPoint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlayerPoint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlayerPoint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlayerPoint().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnRules;
    private javax.swing.JButton btnStart1;
    private javax.swing.JPanel containerPanel;
    private javax.swing.JPanel gameRules;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblPlayer;
    private javax.swing.JLabel lblRules;
    private javax.swing.JLabel riddleMiniLogo;
    private javax.swing.JScrollPane rulesList;
    private javax.swing.JTextField txtPlayerName;
    private javax.swing.JTextArea txtRules;
    // End of variables declaration//GEN-END:variables
}
