/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package riddleproject;
import javax.swing.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
/**
 *
 * @author Laborada
 */
public class RiddlerStart extends javax.swing.JFrame {
    private int currentStoryIndex = 0;
    private int count = 0;
    private String[][][] stories = {
        {{"In the mystical land of Enigmaria, renowned for its love of riddles and puzzles, "
            + "a grand tournament is held every year to find the greatest riddle solver of all. "
            + "Legends speak of a mysterious Riddle Master who resides in the heart of the Enchanted Forest, "
            + "challenging brave souls who seek wisdom and adventure."}, {"Story 1 - Part 2"}}, 
        // First set of stories
        {{"Our protagonist, a young and daring adventurer, hears of this tournament and decides to "
            + "embark on a journey to test their wit and courage. Along the way, they encounter various challenges "
            + "and puzzles, each leading them closer to the Riddle Master's domain."}, {"Story 2 - Part 2"}}  
        // Second set of stories
    };
    private final String[] nextLabels = {"Continue...", "Continue..."};
 
    /**
     * Creates new form RiddlerStart
     */
    public RiddlerStart() {
    initComponents();
        setStory(); // Initialize with the first story
        imgRiddler.setVisible(true);
        imgMC.setVisible(false);
        lblNext.setText(nextLabels[0]); // Set the text of the "Next" button
        
        lblNext.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                // Update the index to navigate to the next story
                currentStoryIndex++;
                count++;
                
                if (currentStoryIndex >= stories.length) {
                    dispose();
                    return;
                }

                // Check if the current story index exceeds the length of stories
                if (currentStoryIndex >= stories.length) {
                    // Reset the story index and navigate to the first story
                    currentStoryIndex = 0;
                }

                setStory(); // Update the story text
                updateNextLabel(); // Update the label of the "Next" button
                if(count == 1){
                    imgRiddler.setVisible(false);
                    imgMC.setVisible(true);
                }
                if(count == 2){
                    storyPanel.setVisible(false);
                    imgMC.setVisible(false);
                    
                }          
            }         
        });
    }
    
   public void setStory() {
        // Construct the story text based on the current story index
        StringBuilder storyBuilder = new StringBuilder("<html>");
        for (String part : stories[currentStoryIndex][0]) {
            storyBuilder.append(part).append("<br>");
        }
        storyBuilder.append("</html>");

        // Set the story text to lblText
        lblText.setText(storyBuilder.toString());
    }
   
    public void updateNextLabel() {
        // Set the text of lblNext to the corresponding label from nextLabels array
        if (currentStoryIndex < nextLabels.length) {
            lblNext.setText(nextLabels[currentStoryIndex]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        storyPanel = new javax.swing.JPanel();
        lblText = new javax.swing.JLabel();
        lblNext = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();
        lblBorderText = new javax.swing.JLabel();
        imgRiddler = new javax.swing.JLabel();
        imgMC = new javax.swing.JLabel();
        imgBG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Guess The Riddle - STORYLINE");
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 750, 500));
        setMaximumSize(new java.awt.Dimension(750, 500));
        setMinimumSize(new java.awt.Dimension(750, 500));
        setSize(new java.awt.Dimension(750, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        storyPanel.setOpaque(false);
        storyPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblText.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        lblText.setForeground(new java.awt.Color(255, 255, 255));
        lblText.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        storyPanel.add(lblText, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 480, 100));

        lblNext.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblNext.setForeground(new java.awt.Color(153, 153, 153));
        lblNext.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblNext.setToolTipText("");
        storyPanel.add(lblNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 440, 120, 30));

        btnNext.setForeground(new java.awt.Color(255, 255, 255));
        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Riddler_imgs/txtBackground.jpg"))); // NOI18N
        btnNext.setAlignmentY(0.0F);
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        storyPanel.add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 540, 130, 20));

        lblBorderText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Riddler_imgs/txtBackground.jpg"))); // NOI18N
        lblBorderText.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        storyPanel.add(lblBorderText, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 520, 160));

        getContentPane().add(storyPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 500));

        imgRiddler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Riddler_imgs/SampleRiddler.png"))); // NOI18N
        getContentPane().add(imgRiddler, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 260, 250));

        imgMC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Riddler_imgs/file.png"))); // NOI18N
        getContentPane().add(imgMC, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 260, 250));

        imgBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Riddler_imgs/MysticLand_BG.jpg"))); // NOI18N
        imgBG.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        imgBG.setMaximumSize(new java.awt.Dimension(750, 500));
        imgBG.setMinimumSize(new java.awt.Dimension(750, 500));
        imgBG.setPreferredSize(new java.awt.Dimension(750, 500));
        getContentPane().add(imgBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RiddlerStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RiddlerStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RiddlerStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RiddlerStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RiddlerStart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNext;
    private javax.swing.JLabel imgBG;
    private javax.swing.JLabel imgMC;
    private javax.swing.JLabel imgRiddler;
    private javax.swing.JLabel lblBorderText;
    private javax.swing.JLabel lblNext;
    private javax.swing.JLabel lblText;
    private javax.swing.JPanel storyPanel;
    // End of variables declaration//GEN-END:variables
}
